name = "DistributedWorkflow"
uuid = "e6614011-adc0-4f34-baa6-5a168cd5013f"
authors = ["FiroozehDastur <dastur.firoozeh@gmail.com>"]
version = "0.1.0"

[deps]
CxxWrap = "1f15a43c-97ca-5a2a-ae31-89f07a497df4"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[compat]
CxxWrap = "v0.14.2"
